[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

#Making Xchip_mod work
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''if effects.jokers.Xmult_mod then mult = mod_mult(mult*effects.jokers.Xmult_mod);extras.mult = true  end'''
position = "after"
payload = '''
--Ortalab/Jokers/Royal Gala
if effects.jokers.Xchip_mod then hand_chips = mod_chips(hand_chips*effects.jokers.Xchip_mod);extras.hand_chips = true end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''sound = extra.edition and 'foil2' or extra.mult_mod and 'multhit1' or extra.Xmult_mod and 'multhit2' or 'generic1'''
position = "after"
payload = '''
--Ortalab/Jokers/Royal Gala
if extra.Xchip_mod then sound = 'multhit2' end
'''
match_indent = true