[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.regex]
target = "functions/state_events.lua"
pattern = '''G\.GAME\.current_round\.free_rerolls = #chaos'''
position = "after"
line_prepend = "$indent"
payload = ''' 
G.GAME.current_round.free_rerolls = G.GAME.current_round.free_rerolls + G.GAME.current_round["olab_free_rerolls"]
'''