[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.regex]
target = "card.lua"
pattern = '''(?<indent>[\t ]*)G\.GAME\.discount_percent = center_table\.extra'''
position = "after"
line_prepend = "$indent"
payload = '''
--Ortalab/Jokers/Black Friday
for k, v in pairs(G.jokers.cards) do
    if v.ability.name == 'Black Friday' then
        G.GAME.discount_percent = G.GAME.discount_percent + 20
    end
end
'''