[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

#Inject for start up
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''G.GAME.current_round.free_rerolls = #chaos'''
position = "after"
payload = '''
--Ortalab/Voucher/Window Shopping & Infinite Scroll
local ortalab_free_rerolls = 0
for k, v in pairs(G.GAME.used_vouchers) do
    if k == 'v_window_shopping' then ortalab_free_rerolls = ortalab_free_rerolls + 1 end
    if k == 'v_infinite_scroll' then ortalab_free_rerolls = ortalab_free_rerolls + 2 end
end
G.GAME.current_round.free_rerolls = G.GAME.current_round.free_rerolls + ortalab_free_rerolls
'''
match_indent = true
overwrite = false